#!/usr/bin/bash

#_                   _ _ _  _ _____ _  _
#| | _______   ____ _| | | || |___  | || |
#| |/ / _ \ \ / / _` | | | || |_ / /| || |_
#|   <  __/\ V / (_| | | |__   _/ / |__   _|
#|_|\_\___| \_/ \__,_|_|_|  |_|/_/     |_|

configure(){

  plain ""

  msg2 "Enable CONFIG_STACK_VALIDATION"
  scripts/config --enable CONFIG_STACK_VALIDATION

  sleep 2s

  msg2 "Enable IKCONFIG"
  scripts/config --enable CONFIG_IKCONFIG
  scripts/config --enable CONFIG_IKCONFIG_PROC

  sleep 2s

  msg2 "Disable NUMA"
  scripts/config --disable CONFIG_NUMA
  scripts/config --disable CONFIG_AMD_NUMA
  scripts/config --disable CONFIG_X86_64_ACPI_NUMA
  scripts/config --disable CONFIG_NODES_SPAN_OTHER_NODES
  scripts/config --disable CONFIG_NUMA_EMU
  scripts/config --disable CONFIG_NEED_MULTIPLE_NODES
  scripts/config --disable CONFIG_USE_PERCPU_NUMA_NODE_ID
  scripts/config --disable CONFIG_ACPI_NUMA
  scripts/config --disable CONFIG_ARCH_SUPPORTS_NUMA_BALANCING
  scripts/config --disable CONFIG_NODES_SHIFT
  scripts/config --undefine CONFIG_NODES_SHIFT
  scripts/config --disable CONFIG_NEED_MULTIPLE_NODES

  sleep 2s

  msg2 "Disable FUNCTION_TRACER/GRAPH_TRACER"
  scripts/config --disable CONFIG_FUNCTION_TRACER
  scripts/config --disable CONFIG_STACK_TRACER

  sleep 2s

  msg2 "Disable CONFIG_USER_NS_UNPRIVILEGED"
  scripts/config --disable CONFIG_USER_NS_UNPRIVILEGED

  sleep 2s

  msg2 "Enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3"
  scripts/config --disable CONFIG_CC_OPTIMIZE_BASAL
  scripts/config --disable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE
  scripts/config --disable CONFIG_CC_OPTIMIZE_FOR_SIZE
  scripts/config --enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3

  sleep 2s

  if [[ $_cpu_sched = "1" ]] || [[ $_cpu_sched = "2" ]]; then
    msg2 "Set timer frequency to 2000HZ"
    scripts/config --enable CONFIG_HZ_2000
    scripts/config --set-val CONFIG_HZ 2000
  else
    msg2 "Set timer frequency to 1000HZ"
    scripts/config --enable CONFIG_HZ_1000
    scripts/config --set-val CONFIG_HZ 1000
  fi

  sleep 2s

  msg2 "Enable ntfs"
  scripts/config --module CONFIG_NTFS_FS
  scripts/config --enable CONFIG_NTFS_RW
  msg2 "Enable ntfs3"
  scripts/config --module CONFIG_NTFS3_FS
  scripts/config --enable CONFIG_NTFS3_64BIT_CLUSTER
  scripts/config --enable CONFIG_NTFS3_LZX_XPRESS
  scripts/config --enable CONFIG_NTFS3_FS_POSIX_ACL

  sleep 2s

  msg2 "Enable BBR/BBR2 TCP"
  scripts/config --module CONFIG_TCP_CONG_BBR
  scripts/config --module CONFIG_TCP_CONG_BBR2

  sleep 2s

  msg2 "Disabling Kyber I/O scheduler"
  scripts/config --disable CONFIG_MQ_IOSCHED_KYBER

  sleep 2s

  msg2 "Enable Deadline I/O scheduler"
  scripts/config --enable CONFIG_MQ_IOSCHED_DEADLINE

  sleep 2s

  msg2 "Enable MQ-Deadline-Nodefault I/O scheduler"
  scripts/config --enable CONFIG_MQ_IOSCHED_DEADLINE_NODEFAULT

  sleep 2s

  msg2 "Enable CONFIG_BFQ_CGROUP_DEBUG"
  scripts/config --enable CONFIG_BFQ_CGROUP_DEBUG

  sleep 2s

  msg2 "Disable debug options"
  scripts/config --disable CONFIG_SLUB_DEBUG
  scripts/config --disable CONFIG_PM_DEBUG
  scripts/config --disable CONFIG_PM_ADVANCED_DEBUG
  scripts/config --disable CONFIG_PM_SLEEP_DEBUG
  scripts/config --disable CONFIG_ACPI_DEBUG
  scripts/config --disable CONFIG_SCHED_DEBUG
  scripts/config --disable CONFIG_LATENCYTOP
  scripts/config --disable CONFIG_DEBUG_PREEMPT
  scripts/config --disable CONFIG_DEBUG_INFO
  scripts/config --disable CONFIG_CGROUP_BPF
  scripts/config --disable CONFIG_BPF_LSM
  scripts/config --disable CONFIG_BPF_PRELOAD
  scripts/config --disable CONFIG_BPF_LIRC_MODE2
  scripts/config --disable CONFIG_BPF_KPROBE_OVERRIDE
  scripts/config --disable CONFIG_DEBUG_INFO_REDUCED
  scripts/config --disable CONFIG_DEBUG_INFO_COMPRESSED
  scripts/config --disable CONFIG_DEBUG_INFO_SPLI
  scripts/config --disable CONFIG_GDB_SCRIPTS
  scripts/config --disable CONFIG_DEBUG_INFO_DWARF4
  scripts/config --disable CONFIG_DEBUG_INFO_BTF
  scripts/config --disable CONFIG_BPF_PRELOAD
  scripts/config --disable CONFIG_BPF_PRELOAD_UMD
  scripts/config --disable CONFIG_BPF_STREAM_PARSER
  scripts/config --disable CONFIG_DMA_API_DEBUG
  scripts/config --disable CONFIG_DMA_API_DEBUG_SG
  scripts/config --disable CONFIG_DMA_MAP_BENCHMARK
  scripts/config --disable CONFIG_DEBUG_FS
  scripts/config --disable CONFIG_GCOV_KERNEL
  scripts/config --disable CONFIG_GCOV_PROFILE_ALL
  scripts/config --disable CONFIG_DEBUG_FS
  scripts/config --disable CONFIG_GENERIC_IRQ_DEBUGFS
  scripts/config --disable CONFIG_ACPI_DEBUGGER
  scripts/config --disable CONFIG_ACPI_DEBUGGER_USER
  scripts/config --disable CONFIG_ACPI_EC_DEBUGFS
  scripts/config --disable CONFIG_ACPI_APEI_ERST_DEBUG
  scripts/config --disable CONFIG_NFIT_SECURITY_DEBUG
  scripts/config --disable CONFIG_DMADEVICES_DEBUG
  scripts/config --disable CONFIG_DMADEVICES_VDEBUG
  scripts/config --disable CONFIG_DMATEST
  scripts/config --disable CONFIG_BTRFS_DEBUG
  scripts/config --disable CONFIG_BTRFS_FS_REF_VERIFY
  scripts/config --disable CONFIG_BTRFS_ASSERT
  scripts/config --disable CONFIG_BTRFS_FS_RUN_SANITY_TESTS
  scripts/config --disable CONFIG_BTRFS_FS_CHECK_INTEGRITY
  scripts/config --disable CONFIG_EXT4_DEBUG
  scripts/config --disable CONFIG_EXT4_KUNIT_TESTS
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG_ASSERTS
  scripts/config --disable CONFIG_SECURITY_APPARMOR_DEBUG_MESSAGES
  scripts/config --disable CONFIG_SECURITY_APPARMOR_KUNIT_TEST
  scripts/config --disable CONFIG_POWER_SUPPLY_DEBUG
  scripts/config --disable CONFIG_NTFS_DEBUG
  scripts/config --disable CONFIG_GENERIC_IRQ_DEBUGFS
  scripts/config --disable CONFIG_CIFS_STATS2
  scripts/config --disable CONFIG_CIFS_DEBUG
  scripts/config --disable CONFIG_CIFS_DEBUG2
  scripts/config --disable CONFIG_CIFS_DEBUG_DUMP_KEYS
  scripts/config --disable CONFIG_JBD2_DEBUG
  scripts/config --disable CONFIG_CONFIG_NFS_DEBUG
  scripts/config --disable CONFIG_TRACE_IRQFLAGS_SUPPORT
  scripts/config --disable CONFIG_TRACE_IRQFLAGS_NMI_SUPPORT
  scripts/config --disable CONFIG_EARLY_PRINTK_USB
  scripts/config --disable CONFIG_X86_VERBOSE_BOOTUP
  scripts/config --disable CONFIG_EARLY_PRINTK
  scripts/config --disable CONFIG_EARLY_PRINTK_DBGP
  scripts/config --disable CONFIG_EARLY_PRINTK_USB_XDBC
  scripts/config --disable CONFIG_EFI_PGT_DUMP
  scripts/config --disable CONFIG_DEBUG_TLBFLUSH
  scripts/config --disable CONFIG_IOMMU_DEBUG
  scripts/config --disable CONFIG_IOMMU_LEAK
  scripts/config --disable CONFIG_HAVE_MMIOTRACE_SUPPORT
  scripts/config --disable CONFIG_X86_DECODER_SELFTEST
  scripts/config --disable CONFIG_IO_DELAY_0X80
  scripts/config --disable CONFIG_IO_DELAY_0XED
  scripts/config --disable CONFIG_IO_DELAY_UDELAY
  scripts/config --disable CONFIG_IO_DELAY_NONE
  scripts/config --disable CONFIG_DEBUG_BOOT_PARAMS
  scripts/config --disable CONFIG_CPA_DEBUG
  scripts/config --disable CONFIG_DEBUG_ENTRY
  scripts/config --disable CONFIG_DEBUG_NMI_SELFTEST
  scripts/config --disable CONFIG_DEBUG_IMR_SELFTEST
  scripts/config --disable CONFIG_X86_DEBUG_FPU
  scripts/config --disable CONFIG_PUNIT_ATOM_DEBUG
  scripts/config --disable CONFIG_UNWINDER_ORC
  scripts/config --disable CONFIG_UNWINDER_FRAME_POINTER
  scripts/config --disable CONFIG_UNWINDER_GUESS
  scripts/config --disable CONFIG_FRAME_POINTER
  scripts/config --disable CONFIG_THINKPAD_ACPI_DEBUGFACILITIES
  scripts/config --disable CONFIG_THINKPAD_ACPI_DEBUG
  scripts/config --disable CONFIG_THINKPAD_ACPI_UNSAFE_LEDS
  scripts/config --disable CONFIG_CMA_DEBUG
  scripts/config --disable CONFIG_CMA_DEBUGFS
  scripts/config --disable CONFIG_EDAC_DEBUG
  scripts/config --disable CONFIG_ATM_IA_DEBUG
  scripts/config --disable CONFIG_ATM_FORE200E_DEBUG
  scripts/config --disable CONFIG_BCMA_DEBUG

  sleep 2s

  msg2 "Enable CONFIG_SCHED_AUTOGROUP_DEFAULT_ENABLED"
  scripts/config --enable CONFIG_SCHED_AUTOGROUP_DEFAULT_ENABLED

  sleep 2s

  msg2 "Enable Fsync support"
  scripts/config --enable CONFIG_FUTEX
  scripts/config --enable CONFIG_FUTEX_PI

  sleep 2s

  msg2 "Enable Futex2 support"
  scripts/config --enable CONFIG_FUTEX2

  sleep 2s

  msg2 "Enable winesync support"
  scripts/config --module CONFIG_WINESYNC

  sleep 2s

  msg2 "Enable SECURITY_FORK_BRUT"
  scripts/config --enable CONFIG_SECURITY_FORK_BRUT

  sleep 2s

  if [[ $_cpu_sched = "1" ]]; then
    msg2 "Enable CacULE CPU scheduler"
    scripts/config --enable CONFIG_CACULE_SCHED
    #msg2 "Disable CFS"
    #scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    #scripts/config --disable CONFIG_CFS_BANDWIDTH
  elif [[ $_cpu_sched = "2" ]]; then
    msg2 "Enable CacULE CPU scheduler"
    scripts/config --enable CONFIG_CACULE_SCHED
    msg2 "Enable CacULE-RDB CPU scheduler..."
    scripts/config --enable CONFIG_CACULE_RDB
    #msg2 "Disable CFS"
    #scripts/config --disable CONFIG_FAIR_GROUP_SCHED
    #scripts/config --disable CONFIG_CFS_BANDWIDTH
  else
    msg2 "Enable CFS"
    scripts/config --enable CONFIG_FAIR_GROUP_SCHED
    scripts/config --enable CONFIG_CFS_BANDWIDTH
  fi

  sleep 2s

  if [[ $_cpu_sched = "1" ]] || [[ $_cpu_sched = "2" ]]; then
    msg2 "Apply suggested config by Hamad Al Marri for CacULE"
    # General Setup
    echo "General Setup"
    sleep 1s
    scripts/config --disable CONFIG_EXPERT
    # Note:
    # CONFIG_NO_HZ_FULL requires you to add
    # the boot parameter "nohz_full=" in your
    # grup. For example, in case your machine
    # has 8 CPUS, "nohz_full=1-7" makes
    # all CPUs (except CPU0) adaptive ticks.
    # Without "nohz_full=1-7", no benfit of
    # selecting CONFIG_NO_HZ_FULL
    #
    # Please see the discussion here:
    # https://github.com/hamadmarri/cacule-cpu-scheduler/discussions/23#discussioncomment-711456
    #scripts/config --enable CONFIG_NO_HZ_FULL

    scripts/config --enable CONFIG_PREEMPT
    scripts/config --enable CONFIG_SCHED_AUTOGROUP
    scripts/config --disable CONFIG_BSD_PROCESS_ACCT
    scripts/config --disable CONFIG_TASK_XACCT
    scripts/config --disable CONFIG_PSI
    scripts/config --disable CONFIG_MEMCG
    scripts/config --disable CONFIG_CGROUP_CPUACCT
    scripts/config --disable CONFIG_CGROUP_DEBUG
    scripts/config --disable CONFIG_CHECKPOINT_RESTORE
    scripts/config --disable CONFIG_SLAB_MERGE_DEFAULT
    scripts/config --disable CONFIG_SLAB_FREELIST_HARDENED
    scripts/config --disable CONFIG_SLUB_CPU_PARTIAL
    scripts/config --disable CONFIG_PROFILING
    # Processor type and features
    echo "Processor type and features"
    sleep 1s
    scripts/config --disable CONFIG_RETPOLINE
    scripts/config --disable CONFIG_X86_5LEVEL
    scripts/config --disable CONFIG_KEXEC
    scripts/config --disable CONFIG_KEXEC_FILE
    scripts/config --disable CONFIG_CRASH_DUMP
    scripts/config --enable HZ_2000
    # ./scripts/config --set_val CONFIG_NR_CPUS (# number of cpus)
    # if you are not using this kernel as guest in a virtual machine,
    # then disable CONFIG_HYPERVISOR_GUEST
    #./scripts/config --disable CONFIG_HYPERVISOR_GUEST
    # Power
    echo "Power"
    sleep 1s
    scripts/config --enable CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
    scripts/config --enable CONFIG_CPU_FREQ_GOV_PERFORMANCE
    scripts/config --disable CONFIG_CPU_FREQ_GOV_ONDEMAND
    # General architecture-dependent options
    scripts/config --disable CONFIG_KPROBES
    # Kernel hacking
    echo "Kernel hacking"
    scripts/config --disable CONFIG_FTRACE
    scripts/config --disable CONFIG_DEBUG_KERNEL
    scripts/config --disable CONFIG_PAGE_EXTENSION
    scripts/config --set-val CONFIG_RCU_CPU_STALL_TIMEOUT 4
    scripts/config --disable CONFIG_PRINTK_TIME
    scripts/config --disable CONFIG_DEBUG_INFO
    scripts/config --disable CONFIG_ENABLE_MUST_CHECK
    scripts/config --disable CONFIG_STRIP_ASM_SYMS
    scripts/config --disable CONFIG_UNUSED_SYMBOLS
    scripts/config --disable CONFIG_DEBUG_FS
    scripts/config --disable CONFIG_OPTIMIZE_INLINING
    scripts/config --disable CONFIG_DEBUG_SECTION_MISMATCH
    scripts/config --disable CONFIG_SECTION_MISMATCH_WARN_ONLY
    scripts/config --disable CONFIG_STACK_VALIDATION
    scripts/config --disable CONFIG_DEBUG_FORCE_WEAK_PER_CPU
    scripts/config --disable CONFIG_MAGIC_SYSRQ
    scripts/config --disable CONFIG_MAGIC_SYSRQ_SERIAL
    scripts/config --disable CONFIG_PAGE_EXTENSION
    scripts/config --disable CONFIG_DEBUG_PAGEALLOC
    scripts/config --disable CONFIG_PAGE_OWNER
    scripts/config --disable CONFIG_DEBUG_MEMORY_INIT
    scripts/config --disable CONFIG_HARDLOCKUP_DETECTOR
    scripts/config --disable CONFIG_SOFTLOCKUP_DETECTOR
    scripts/config --disable CONFIG_DETECT_HUNG_TASK
    scripts/config --disable CONFIG_WQ_WATCHDOG
    scripts/config --set-val CONFIG_PANIC_TIMEOUT 10
    scripts/config --disable CONFIG_SCHED_DEBUG
    scripts/config --disable CONFIG_SCHEDSTATS
    scripts/config --disable CONFIG_SCHED_STACK_END_CHECK
    scripts/config --disable CONFIG_STACKTRACE
    scripts/config --disable CONFIG_DEBUG_BUGVERBOSE
    scripts/config --set-val CONFIG_RCU_CPU_STALL_TIMEOUT 4
    scripts/config --disable CONFIG_RCU_TRACE
    scripts/config --disable CONFIG_FAULT_INJECTION
    scripts/config --disable CONFIG_LATENCYTOP
    scripts/config --disable CONFIG_PROVIDE_OHCI1394_DMA_INIT
    scripts/config --disable RUNTIME_TESTING_MENU
    scripts/config --disable CONFIG_MEMTEST
    scripts/config --disable CONFIG_KGDB
    scripts/config --disable CONFIG_EARLY_PRINTK
    scripts/config --disable CONFIG_DOUBLEFAULT

    sleep 2s
  fi

  msg2 "Set CONFIG_GENERIC_CPU"
  scripts/config --enable CONFIG_GENERIC_CPU

  sleep 2s
}
